services:
- type: web
  name: ghost
  plan: free
  env: docker
  autoDeploy: false
  disk:
    name: ghost
    mountPath: /var/lib/ghost/content
    sizeGB: 10 #Feel free to change this to suit your needs.


